version: "3"

vars:
  BACKEND_PORT: 8100
  FRONTEND_PORT: 3000
  BACKEND_DIR: "{{.ROOT_DIR}}"
  FRONTEND_DIR: "{{.ROOT_DIR}}/ui"

tasks:
  setup:
    desc: Setup development environment (venv + dependencies)
    cmds:
      - rm -rf .venv
      - python3 -m venv .venv
      - .venv/bin/python -m ensurepip
      - .venv/bin/pip install --upgrade pip setuptools wheel
      - .venv/bin/pip install -e .
      - task: install:frontend

  install:
    desc: Install dependencies for both backend and frontend
    cmds:
      - task: install:backend
      - task: install:frontend

  install:backend:
    desc: Install Python dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - .venv/bin/pip install -e .

  install:frontend:
    desc: Install Node.js dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm install

  dev:
    desc: Start both backend and frontend in development mode
    deps:
      - dev:backend
      - dev:frontend

  dev:backend:
    desc: Start backend API server
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - .venv/bin/python converter_api.py
    env:
      PORT: "{{.BACKEND_PORT}}"

  dev:frontend:
    desc: Start frontend development server
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run dev
    env:
      NEXT_PUBLIC_API_URL: http://localhost:{{.BACKEND_PORT}}
      PORT: "{{.FRONTEND_PORT}}"

  test:api:
    desc: Run API tests
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - .venv/bin/pytest api-tests/ -v

  loadtest:run:
    desc: Run k6 load test against localhost:8100
    dir: "{{.ROOT_DIR}}"
    cmds:
      - |
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        NANO_CPUS=$(docker inspect sqlglot-backend -f '{{"{{"}} .HostConfig.NanoCpus {{"}}"}}')
        CORES=$(echo "scale=1; $NANO_CPUS / 1000000000" | bc)
        MEM_BYTES=$(docker inspect sqlglot-backend -f '{{"{{"}} .HostConfig.Memory {{"}}"}}')
        MEMORY=$(echo "scale=0; $MEM_BYTES / 1048576" | bc)
        WORKERS=$(docker exec sqlglot-backend printenv E6_UVICORN_WORKERS 2>/dev/null || echo "unknown")
        FILENAME="load-tests/results/${TIMESTAMP}_${CORES}core_${MEMORY}M_${WORKERS}workers.json"
        mkdir -p load-tests/results
        echo "Running k6 test, results will be saved to ${FILENAME}"
        k6 run --summary-export="${FILENAME}" load-tests/inline-transpile.js

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.FRONTEND_DIR}}/.next
      - rm -rf {{.FRONTEND_DIR}}/node_modules
      - find {{.BACKEND_DIR}} -type d -name "__pycache__" -exec rm -rf {} +
      - find {{.BACKEND_DIR}} -type f -name "*.pyc" -delete